### PR TITLE
Fixing Deployment - removing unused fastboot implementation

### PR DESCRIPTION
**Pull request by mansona**
So after a conversation yesterday on Slack I finally figured out that the fastboot implementation wasn't being used 🙈 I knew there was something funny going on because a lot of the fastboot code was broken in such a way that I suspect it has never worked 🤪 

This PR greatly simplifies the deployment of this code 💪 You may notice that I'm deleting the Proc file, that's because this is now just a static file deployment. Essentially all we need to do is run `ember build -prod` and deploy the resulting `dist` folder using a static buildpack. 

I also deleted the ember-cli-deploy implementation because it wasn't actually configured to do anything other than essentially run `ember build -prod`.

Let me know if you have any questions 👍

### CODE REVIEW

**Comment by lmerriam** [comment]
Hit "create review app" in the Heroku pipeline, got this back:

Could not create review app. This app is using the Cedar-14 stack, which
has been end-of-life since May 1st, 2019. The building of Cedar-14 apps is
no longer supported as of November 2nd, 2020. Please update to the latest
stack to deploy new versions of your code to this app:
https://devcenter.heroku.com/articles/upgrading-to-the-latest-stack For
more information: https://help.heroku.com/SMQ1J712/cedar-14-end-of-life-faq.
• View log

**Comment by mansona** [comment]
@lmerriam I did a bit of research and it seems like we can't make use of the review apps with the monorepo setup 😞 at least they won't take up the app.json that I added in this PR because it would need to load the monorepo buildpack to know where to find the app.json that tells it to load the monorepo buildpack 🙃 

I think it's fine for us to just use staging as our testing ground 👍 I tested this implementation with a personal heroku and doing the old-school `git push heroku` way of doing it so I'm happy that we've solved the main issues

**Review by compwron — APPROVED** [review]
This is exciting and wonderful and I definitely don't fully understand it. Lets put it in staging!!!

**Comment by mansona** [comment]
I know we're currently putting in the effort to get things back up and running but if you ever want to circle back to these PRs and have me walk you through what's going on just let me know 👍

**Pull request merged**
