### PR TITLE
Fully automated CD pipeline

### PR DESCRIPTION
**Pull request by benlangfeld**
The intent here is to build a unified deployment pipeline for all application components (frontend and api) in an automated fashion which can be independently reproduced. It is related to https://github.com/rubyforgood/Flaredown/issues/466

### CODE REVIEW

**Comment by benlangfeld** [comment]
Review apps were ruled out in https://github.com/rubyforgood/Flaredown/pull/430#issuecomment-904351074, but I think we can figure it out.

**Comment by compwron** [comment]
When this is merged, how will the app be deployed, and who will have access to do so?

**Comment by benlangfeld** [comment]
> When this is merged, how will the app be deployed, and who will have access to do so?

Either a team would be defined for it, or members added directly to the pipelines, but both would be defined by Terraform.

This is firmly WIP; I hope to get back to it some time in the next few weeks.

**Comment by compwron** [comment]
@benlangfeld  I would love to take this further and get it merged when you have time :)

**Comment by compwron** [comment]
I'm not sure how this works or what to do with it, so closing for now. I am open to it getting reopened and completed. 
Something to keep in mind is that flaredown may have to move off of heroku when the ruby for good heroku credits don't get renewed.

**Pull request closed without merging**
