### PR TITLE
333 enable fastboot

### PR DESCRIPTION
**Pull request by X-tina**

### CODE REVIEW

**Comment by lmerriam** [comment]
Here's what I recorded using chrome's network tab: https://paper.dropbox.com/doc/Flaredown-Fastboot-Performance-l4Kv4NCoZ0TmRMX8PzfSR

It looks like fastboot is actually slower in most cases, is there anything I can do to help figure out the cause of the slowdown?

**Comment by X-tina** [comment]
@lmerriam 
it's proper, that the total time for page rendering is bigger, when Fastboot is on; that's because of the nature of how Fastboot works: (1) it creates a Node.js process prior to start executing the Ember.js application; (2) it pre-processes templates and produces HTML+CSS on a server and responds with the result to a user - that results in increase of the total response time.

I've consulted with CTO and our devOps and we've come up with idea. Our devOps can add some settings on Heroku to devide requests from robot crawler (and turn on Fastboot) and from regular user (turn off the last one). This should increase the PWA.

**Comment by lmerriam** [comment]
@X-tina I agree that the **total** load times should be longer. But the DOM content should load in faster because with Fastboot the server will render it first before loading all of the JS, and I'm seeing the `DomContentLoaded` event firing slower in all cases.

Let me know if I'm misunderstanding! But from everything I've read it finish the initial loading of the static content faster and improve perceived speed that way.

**Comment by compwron** [comment]
I am closing this as too stale for now.

**Pull request closed without merging**
